 import { Inter, Playfair_Display } from 'next/font/google'
import './global.css'

 
const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
})

 
const playfair = Playfair_Display({
	variable: '--font-playfair',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
			className={`${inter.variable} ${playfair.variable} h-screen antialiased`}
		>
			<body className='min-h-full flex flex-col font-(--font-inter)'>
				<main className='min-h-screen'>{children}</main>
			</body>
		</html>
	)
}