  import { Inter, Playfair_Display } from 'next/font/google'
import './global.css'
import Navbar from '../components/layout/Navbar'
import Footer from '../components/layout/Footer'
import NextThemeProvider from '../providers/NextThemeProvider'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
})

const playfair = Playfair_Display({
	variable: '--font-playfair',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html
			lang='en'
			suppressHydrationWarning
			className={`${inter.variable} ${playfair.variable} h-screen antialiased`}
		>
			<body className='min-h-full flex flex-col font-(--font-inter)'>
				<NextThemeProvider>
					<ToastContainer />
					<Navbar />
					<main className='flex-1'>{children}</main>
					<Footer />
				</NextThemeProvider>
				 
        
			</body>
		</html>
	)
}